import Dexie, { type EntityTable } from 'dexie';

import type { TradeEventV1 } from '../domain/activity';
import { NETWORK_CATALOG } from '../fomo/network-map';
import {
  createEventAliasRecords,
  reclassifyUnknownChainEvents,
  type EventAliasRecord,
} from './event-repository';

import type { MetricCacheRecord } from './metric-repository';

const EVENTS_SCHEMA =
  'id, occurredAt, [traderId+occurredAt], [chain+occurredAt], [tokenAddress+occurredAt], readAt';
const METRICS_SCHEMA = 'traderId, expiresAt';
const EVENT_ALIASES_SCHEMA = 'aliasKey, canonicalEventId';

const LEGACY_DOM_DUPLICATE_WINDOW_MS = 90_000;

function isLegacyDomPresentation(event: TradeEventV1): boolean {
  return event.source === 'fomo'
    && event.sourceTradeId !== undefined
    && event.traderAvatarUrl === undefined
    && (event.traderName === undefined || event.traderName === event.traderHandle);
}

function isAuthoritativeTwin(
  candidate: TradeEventV1,
  other: TradeEventV1,
): boolean {
  return other.id !== candidate.id
    && other.source === 'fomo'
    && other.traderHandle === candidate.traderHandle
    && other.action === candidate.action
    && other.tokenAddress === candidate.tokenAddress
    && other.usdAmount === candidate.usdAmount
    && Math.abs(other.occurredAt - candidate.occurredAt) <= LEGACY_DOM_DUPLICATE_WINDOW_MS
    && (other.traderAvatarUrl !== undefined || other.traderName !== other.traderHandle);
}

export class FomoFeedDatabase extends Dexie {
  events!: EntityTable<TradeEventV1, 'id'>;
  metrics!: EntityTable<MetricCacheRecord, 'traderId'>;
  eventAliases!: EntityTable<EventAliasRecord, 'aliasKey'>;

  constructor(name = 'fomo-live-feed') {
    super(name);

    this.version(1).stores({
      events: EVENTS_SCHEMA,
      metrics: METRICS_SCHEMA,
    });

    // Version 2 (Task 3): unknown-chain reclassification migration.
    //
    // Rows stored as chain 'unknown' with a networkId that has since been
    // VERIFIED against a real authenticated Fomo capture are reclassified to
    // their resolved chain (see reclassifyUnknownChainEvents for the exact
    // predicates). The six product entries are now verified-from-capture
    // (docs/evidence/fomo-network-catalog.md), so this upgrade becomes active
    // for stored unknown rows that match those IDs. The operation is
    // idempotent, so re-running it across upgrades is safe.
    this.version(2)
      .stores({
        events: EVENTS_SCHEMA,
        metrics: METRICS_SCHEMA,
      })
      .upgrade(async () => {
        const verifiedMappings = new Map(
          NETWORK_CATALOG.filter(
            (entry) => entry.status === 'verified-from-capture',
          ).map((entry) => [entry.networkId, entry.chain] as const),
        );

        await reclassifyUnknownChainEvents(this.events, verifiedMappings);
      });

    // Version 3 removes rows produced by the first DOM fallback parser. That
    // parser could mistake token-detail controls for feed activity. The
    // migration runs once; correctly parsed visible rows are then captured
    // again by the tightened observer, while socket-originated history stays
    // untouched.
    this.version(3)
      .stores({
        events: EVENTS_SCHEMA,
        metrics: METRICS_SCHEMA,
      })
      .upgrade(async () => {
        await this.events
          .filter((event) => event.sourceEventId?.startsWith('dom-') === true)
          .delete();
      });

    // Version 4 removes DOM rows whose derived identity included mutable
    // relative time and market-cap text. Stable tradeId-backed rows are
    // recaptured after upgrade; socket and Pump history is preserved.
    this.version(4)
      .stores({
        events: EVENTS_SCHEMA,
        metrics: METRICS_SCHEMA,
      })
      .upgrade(async () => {
        await this.events
          .filter((event) => event.sourceEventId?.startsWith('dom-') === true)
          .delete();
      });

    // Version 5 gives stable source-scoped identities their own table. Event
    // persistence writes an event and its aliases in one transaction, so a
    // worker restart cannot leave a replay window between the two writes.
    this.version(5)
      .stores({
        events: EVENTS_SCHEMA,
        metrics: METRICS_SCHEMA,
        eventAliases: EVENT_ALIASES_SCHEMA,
      })
      .upgrade(async () => {
        const records = (await this.events.toArray())
          .flatMap((event) => createEventAliasRecords(event));
        if (records.length > 0) {
          await this.eventAliases.bulkPut(records);
        }
      });

    // Version 6 removes the remaining rows generated by the DOM recovery
    // parser without a stable trade identity. Version 5 could still create
    // them while the WebSocket/API channel was healthy, so they duplicate
    // the authoritative source event. Only the explicit DOM marker is
    // removed; all Fomo socket/API and Pump rows remain untouched.
    this.version(6)
      .stores({
        events: EVENTS_SCHEMA,
        metrics: METRICS_SCHEMA,
        eventAliases: EVENT_ALIASES_SCHEMA,
      })
      .upgrade(async () => {
        await this.events
          .filter((event) => event.sourceEventId?.startsWith('dom-') === true)
          .delete();
      });

    // Version 7 repeats the cleanup for profiles that had already advanced
    // their schema version before the v6 build was loaded. The predicate is
    // idempotent and only touches synthetic DOM identities.
    this.version(7)
      .stores({
        events: EVENTS_SCHEMA,
        metrics: METRICS_SCHEMA,
        eventAliases: EVENT_ALIASES_SCHEMA,
      })
      .upgrade(async () => {
        await this.events
          .filter((event) => event.sourceEventId?.startsWith('dom-') === true)
          .delete();
      });

    // Version 8 reconciles a short-lived build that stored DOM rows under a
    // trade ID instead of the former `dom-*` marker. Only remove a row with
    // the DOM presentation shape when an otherwise identical, richer Fomo
    // record exists within the capture window. This avoids fuzzy deletion of
    // genuine repeated trades.
    this.version(8)
      .stores({
        events: EVENTS_SCHEMA,
        metrics: METRICS_SCHEMA,
        eventAliases: EVENT_ALIASES_SCHEMA,
      })
      .upgrade(async () => {
        const rows = await this.events.toArray();
        const duplicateIds = rows
          .filter((event) => isLegacyDomPresentation(event))
          .filter((candidate) => rows.some((other) => isAuthoritativeTwin(candidate, other)))
          .map((event) => event.id);

        if (duplicateIds.length > 0) {
          await this.events.bulkDelete(duplicateIds);
        }
      });
  }
}
